[server]
hostname = "wso2am"
node_ip = "127.0.0.1"
server_role = "default"

[user_store]
type = "database_unique_id"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.apim_db]
type = "postgresql"
url = "jdbc:postgresql://aqua-cicd-app-uat-postgresql.cluster-xxx.ap-southeast-1.rds.amazonaws.com:5432/wso2am"
username = "wso2user"
password = "$env{DB_PASSWORD}"

[database.shared_db]
type = "postgresql"
url = "jdbc:postgresql://aqua-cicd-app-uat-postgresql.cluster-xxx.ap-southeast-1.rds.amazonaws.com:5432/wso2shared"
username = "wso2user"
password = "$env{DB_PASSWORD}"

[keystore.tls]
file_name = "wso2carbon.jks"
type = "JKS"
password = "wso2carbon"
alias = "wso2carbon"
key_password = "wso2carbon"

[transport.https.properties]
proxyPort = 443

[apim.gateway.environment.Default]
ws_endpoint = "ws://wso2am:9099"
wss_endpoint = "wss://wso2am:8099"
http_endpoint = "http://wso2am:8280"
https_endpoint = "https://wso2am:8243"

[apim.analytics]
enable = false